### ISSUE TITLE
UDH support for sending large messages

### ISSUE THREAD

**Issue by haisum** [CodeMonkeyKevin/smpp34#15]
There's no way of sending UDH data for concatenated sms as described in https://en.wikipedia.org/wiki/Concatenated_SMS#Sending_a_concatenated_SMS_using_a_User_Data_Header

There are other ways like using Sar_* tlv fields or message_payload TLV field for sending concatenated sms but they aren't supported by all smpp servers. Only reliable way is to use UDH headers. Any suggestion on how I might be able to send multiple messages as one big message  using this library?

**Comment by CodeMonkeyKevin** [comment]
Would you be able to provide a sample UHD PDU (preferably in hex)?

\Kevin

**Comment by haisum** [comment]
check https://help.nexmo.com/hc/en-us/articles/204015653-Sending-Concatenated-Messages

and there's a java example here https://itprobes.wordpress.com/2009/09/05/hello-world/

**Comment by uriel-fanelli** [comment]
Why you say you cannot? Usually UDHi is sent into the payload of the message itself, after setting the esm_class accordingly. 

So you set, by example, esm_class to 0x40 , and then you can prepend the UDHi to the message segment, having care of respecting the syntax for concatenation, which is the same thing the post is saying....

**Comment by haisum** [comment]
You're right, I did solve  this problem as you suggested but forgot to mention here.
